export const formTypes = [
  {
    label: '基础控件',
    children: [
      { label: '单行输入', value: 'input' },
      { label: '多行输入', value: 'textarea' },
      { label: '数字输入', value: 'number' },
      { label: '开关', value: 'switch' },
      { label: '单选框组', value: 'radio' },
      { label: '多选框组', value: 'checkbox' },
      { label: '下拉选择', value: 'select' },
      { label: '级联选择', value: 'cascader' },
      { label: '日期选择', value: 'date' },
      { label: '时间选择', value: 'time' },
      { label: '文件上传', value: 'file' },
      { label: '图片上传', value: 'image' },
      { label: '颜色选择', value: 'color' },
      { label: '评分', value: 'rate' },
      { label: '滑块', value: 'slider' },
      { label: '富文本', value: 'richtext' },
      { label: '提示', value: 'tip' },
    ],
  },
  {
    label: '高级控件',
    children: [
      { label: '组织选择', value: 'org' },
      { label: '部门选择', value: 'dept' },
      { label: '岗位选择', value: 'position' },
      { label: '用户选择', value: 'user' },
      { label: '角色选择', value: 'role' },
      { label: '下拉树型', value: 'tree' },
      { label: '单据组件', value: 'bill' },
      { label: '下拉表格', value: 'table' },
      { label: '赋值子表', value: 'subtable' },
      { label: '省市区域', value: 'area' },
      { label: '关联表单', value: 'form' },
      { label: '弹框选择', value: 'dialog' },
      { label: '扫描条码', value: 'barcode' },
    ],
  },
  {
    label: '系统控件',
    children: [
      { label: '创建人员', value: 'creator' },
      { label: '创建时间', value: 'createTime' },
      { label: '修改人员', value: 'modifier' },
      { label: '修改时间', value: 'modifyTime' },
      { label: '所属组织', value: 'belongOrg' },
      { label: '所属岗位', value: 'belongPosition' },
    ],
  },
];
